## @section
##
## @descriptionStart
## **Prerequisites:**
## - External Secrets Operator 0.15.1+ installed with all CRDs `ExternalSecret`, `ClusterSecretStore`, and `SecretStore`
## - A secret store (`ClusterSecretStore` or `SecretStore`) created and configured to access the external store (e.g., HashiCorp Vault, AWS Secrets Manager, etc.)
## @descriptionEnd
## @param storeName The name of the secret store
## @extra storeKind The kind of the secret store. `ClusterSecretStore` or `SecretStore`. If undefined (the default), set to `null` or `""` then `ClusterSecretStore` is used.
## @param secretName The name of the ExternalSecret & the Kubernetes Secret that will be created
## @param refreshInterval The interval at which the ExternalSecret will be refreshed
## @extra creationPolicy The creation policy of the ExternalSecret. `Owner`, `Merge`, or `None`. If undefined (the default), set to `null` or `""`, then `Owner` is used.
## @param remoteRefPath The path in the external store (e.g., Vault) where all the secrets defined in the `secrets` array are stored. If not provided, the parameter must be set for each secret in the `secrets` array.
## @param secrets Array of secrets to be retrieved from the external store and stored in the Kubernetes Secret
## @extra secrets.[].key The key of the secret in the Kubernetes Secret.
## @extra secrets.[].remoteRefPath The path to the secret in the external store if it is different from `remoteRefPath` or `remoteRefPath` is not provided.
## @extra secrets.[].remoteKey The key of the secret in the external store if it is different from `secrets.[].key`.
## @param targetTemplate Use this to set a custom template for the target secret (see https://external-secrets.io/latest/guides/templating/). This is useful for advanced use cases where you want to customize the secret data or type.
storeName: ""
secretName: "{{ .Release.Name }}-external-secret"
refreshInterval: "1h"
remoteRefPath: "secret/path/in/vault"
secrets: []
  # - key: ""
  #   remoteKey: ""
  #   remoteRefPath: ""
targetTemplate: {}
  # type: kubernetes.io/dockerconfigjson
  # engineVersion: v2
  # data:
  #   .dockerconfigjson: "{{ `{{ .mysecret }}` }}"

## @param extraObjects Array of extra ExternalSecret resources to be created. This is useful for creating additional resources that are not part of the main ExternalSecret spec, such type or different secret stores. NOTE: the main `storeName` defined above will be used if not provided in the extra object.
extraObjects: []
  # - storeName: ""
  #   secretName: ""
  #   refreshInterval: ""
  #   remoteRefPath: ""
  #   secrets:
  #     - key: ""
  #       remoteKey: ""
  #       remoteRefPath: ""
  #   targetTemplate: {}
