{{- if not .Values.secrets -}}
{{- fail "No secrets were provided. Please provide at least one secret in the secrets array." -}}
{{- end -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl .Values.secretName . }}
spec:
  refreshInterval: {{ .Values.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: {{ .Values.storeKind | default "ClusterSecretStore" }}
    name: {{ .Values.storeName }}
  target:
    name: {{ tpl .Values.secretName . }}
    creationPolicy: {{ .Values.creationPolicy | default "Owner" }}
  data:
    {{- range .Values.secrets }}
    - secretKey: {{ .key | quote }}
      remoteRef:
        key: {{ default $.Values.remoteRefPath .remoteRefPath | quote }}
        property: {{ default .key .remoteKey | quote }}
    {{- end -}}
