{{- if .Values.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl .Values.secretName . }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.storeKind }}
    name: {{ .Values.storeName }}
  target:
    {{- with .Values.targetTemplate }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    name: {{ tpl .Values.secretName . }}
    creationPolicy: {{ .Values.creationPolicy }}
  data:
    {{- range $key, $val := .Values.secrets }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ (dict $val).remoteRefPath | default $.Values.remoteRefPath | quote }}
        property: {{ (dict $val).remoteKey | default $key | quote }}
    {{- end -}}
{{- range .Values.extraObjects }}
{{- if .secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl .secretName . }}
spec:
  refreshInterval: {{ coalesce .refreshInterval $.Values.refreshInterval }}
  secretStoreRef:
    kind: {{ coalesce .storeKind $.Values.storeKind }}
    name: {{ coalesce .storeName $.Values.storeName }}
  target:
    {{- with .targetTemplate }}
    template:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    name: {{ tpl .secretName . }}
    creationPolicy: {{ coalesce .creationPolicy $.Values.creationPolicy }}
  data:
    {{- $remoteRefPath := .remoteRefPath | default $.Values.remoteRefPath }}
    {{- range $key, $val := .Values.secrets }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ (dict $val).remoteRefPath | default $remoteRefPath | quote }}
        property: {{ (dict $val).remoteKey | default $key | quote }}
    {{- end -}}
{{- end }}
{{- end }}
{{- end -}}