{{- range $key, $val := .Values.secrets }}
{{- $pushsecret := merge (default dict .pushsecret) (default dict $.Values.pushsecret) }}
{{- if $pushsecret.enabled }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name (regexReplaceAll "[^a-zA-Z0-9]+" $key "-" | lower) }}
spec: 
  updatePolicy: {{ $pushsecret.updatePolicy }}
  {{- with $pushsecret.deletionPolicy }}
  deletionPolicy: {{ . }}
  {{- end }}
  {{- with $pushsecret.refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  secretStoreRefs:
    - name: {{ $.Values.storeName }}
      kind: {{ $.Values.storeKind }}
  selector:
    generatorRef:
      apiVersion: {{ $pushsecret.generatorRef.apiVersion | default "generators.external-secrets.io/v1alpha1" }}
      kind: {{ $pushsecret.generatorRef.kind | default "ClusterGenerator" }}
      name: {{ $pushsecret.generatorRef.name }}
  data:
    - match:
        secretKey: {{ $pushsecret.generatorRef.outputKey | default "password" }}
        remoteRef:
          remoteKey: {{ trimPrefix "secret/" ($val.remoteRefPath | default $.Values.remoteRefPath) }}
          property: {{ $val.remoteKey | default $key }}
---
{{- end }}
{{- end }}