{{- range .Values.secrets }}
{{- if or $.Values.pushsecret .pushsecret }}
{{- $pushsecret := merge (default dict $.Values.pushsecret) (default dict .pushsecret) }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-%s" $.Release.Name (regexReplaceAll "[^a-zA-Z0-9]+" .key "-" | lower) }}
  spec: 
    updatePolicy: {{ $pushsecret.updatePolicy }}
    refreshInterval: {{ $pushsecret.refreshInterval }}
    secretStoreRefs:
      - name: {{ $.Values.storeName }}
        kind: {{ $.Values.storeKind | default "ClusterSecretStore" }}
    selector:
      generatorRef:
        apiVersion: {{ $pushsecret.generatorRef.apiVersion | default "generators.external-secrets.io/v1alpha1" }}
        kind: {{ $pushsecret.generatorRef.kind | default "ClusterGenerator" }}
        name: {{ $pushsecret.generatorRef.name }}
    data:
      - match:
          secretKey: {{ .key }}
          remoteRef:
            remoteKey: {{ .remoteRefPath | default $.Values.remoteRefPath }}
            property: {{ .remoteKey | default .key }}
---
{{- end }}
{{- end }}