{{- range .Values.secrets }}
{{- if or $.Values.pushsecret .pushsecret }}
{{- $pushsecret := merge (default dict $.Values.pushsecret) (default dict .pushsecret) }}
apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: {{ printf "%s-%s" .Release.Name (regexReplaceAll "[^a-zA-Z0-9]+" .Key "-")}}
{{- end }}